import bpy,json,hashlib,argparse,sys
from pathlib import Path
ap=argparse.ArgumentParser();ap.add_argument('--root',default=str(Path(__file__).resolve().parents[1]));ap.add_argument('--candidate');ap.add_argument('--output-dir');args=ap.parse_args(sys.argv[sys.argv.index('--')+1:] if '--' in sys.argv else []);r=Path(args.root);outdir=Path(args.output_dir) if args.output_dir else r/'independent_review';outdir.mkdir(parents=True,exist_ok=True);candidate=Path(args.candidate) if args.candidate else r/'release/source/AetherLab_Global_World_Blockout_v1.blend'
source_sha256=hashlib.sha256(candidate.read_bytes()).hexdigest()
def take(f):
 bpy.ops.wm.open_mainfile(filepath=str(f));m=bpy.data.objects['WORLD_Terrain_Continuous_800x800m'].data
 vs={tuple(v.co[:2]):v.co.z for v in m.vertices}
 faces={tuple(sorted(tuple(m.vertices[i].co[:2]) for i in p.vertices)):{'smooth':p.use_smooth,'material':m.materials[p.material_index].name} for p in m.polygons}
 return vs,faces
b,bf=take(r/'input/AetherLab_Global_World_Blockout_v1.blend');a,af=take(candidate);common=set(b)&set(a);changed=[(xy,b[xy],a[xy]) for xy in common if abs(b[xy]-a[xy])>1e-6];smooth=[k for k in bf if k in af and bf[k]['smooth']!=af[k]['smooth']];new=[xy for xy in a if xy not in b]
x={'reviewer_script_sha256':hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),'source_sha256':source_sha256,'source_unchanged':source_sha256==hashlib.sha256(candidate.read_bytes()).hexdigest(),'original_xy_vertex_count':len(b),'candidate_xy_vertex_count':len(a),'retained_original_xy_count':len(common),'removed_original_xy_count':len(set(b)-set(a)),'added_xy_count':len(new),'changed_original_z_count':len(changed),'changed_original_xy_bounds':[[min(c[0][i] for c in changed),max(c[0][i] for c in changed)] for i in [0,1]],'added_xy_bounds':[[min(c[i] for c in new),max(c[i] for c in new)] for i in [0,1]],'matched_original_faces_smoothing_changed':len(smooth),'smoothing_change_xy_bounds':None if not smooth else [[min(p[i] for k in smooth for p in k),max(p[i] for k in smooth for p in k)] for i in [0,1]],'all_candidate_face_materials':sorted(set(x['material'] for x in af.values())),'note':'Material slot reassignment is global; the new material is derived from original with local zero-outside-mask additional blend. Raw original material datablocks independently compared exact.'};(outdir/'Terrain_Scope_Probe.json').write_text(json.dumps(x,indent=2));print(json.dumps(x,indent=2))
